name: Build Resume PDF

on:
  push:
    paths:
      - 'resume.tex'
      - '.github/workflows/build-resume.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: |
          scheme-basic
          latexmk
          enumitem
          titlesec
          marvosym
          fullpage
          fancyhdr
          hyperref
    
    - name: Build Resume PDF
      run: |
        mkdir -p assets/pdf
        pdflatex -output-directory=assets/pdf resume.tex
        pdflatex -output-directory=assets/pdf resume.tex
        rm -f assets/pdf/*.aux assets/pdf/*.log assets/pdf/*.out
    
    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/pdf/resume.pdf
        git diff --staged --quiet || git commit -m "Update resume PDF"
        git push || echo "No changes to push"