name: Generate Resume PDFs

on:
  push:
    paths:
      - 'content/resume/**'
      - '.github/workflows/resume-generator.yml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the resume'
        required: false
        default: 'latest'

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-full
          pip install pyyaml jinja2 markdown

      - name: Create resume directory structure
        run: |
          mkdir -p content/resume
          mkdir -p static/files/resume-versions
          mkdir -p scripts

      - name: Create resume generator script
        run: |
          cat > scripts/generate_resume.py << 'EOF'
          import yaml
          import json
          from datetime import datetime
          import subprocess
          import os
          from jinja2 import Template

          def load_resume_data():
              """Load resume data from YAML file"""
              try:
                  with open('content/resume/data.yaml', 'r') as f:
                      return yaml.safe_load(f)
              except FileNotFoundError:
                  # Return sample data if file doesn't exist
                  return {
                      'name': 'Linji (Joey) Wang',
                      'email': 'joewwang@outlook.com',
                      'phone': '+1 412-888-6071',
                      'linkedin': 'linkedin.com/in/linjiw',
                      'github': 'github.com/linjiw',
                      'website': 'linjiwang.com',
                      'education': [
                          {
                              'degree': 'Ph.D. in Computer Science',
                              'institution': 'George Mason University',
                              'year': '2023 - Present',
                              'details': 'Research focus: AI, Robotics, Reinforcement Learning'
                          },
                          {
                              'degree': 'M.Sc. in Mechanical Engineering',
                              'institution': 'Carnegie Mellon University',
                              'year': '2021 - 2023',
                              'details': 'GPA: 3.8/4.0'
                          },
                          {
                              'degree': 'B.Sc. in Mechanical Engineering',
                              'institution': 'University of Cincinnati',
                              'year': '2017 - 2021',
                              'details': 'Summa Cum Laude'
                          }
                      ],
                      'experience': [
                          {
                              'title': 'Teaching Assistant',
                              'company': 'Carnegie Mellon University',
                              'period': '2022 - 2023',
                              'bullets': [
                                  'Assisted in Machine Learning and Deep Learning courses',
                                  'Mentored 50+ students in project implementations'
                              ]
                          },
                          {
                              'title': 'Research Assistant',
                              'company': 'Computational Engineering & Robotics Lab',
                              'period': '2021 - 2023',
                              'bullets': [
                                  'Developed computer vision algorithms for 3D scene understanding',
                                  'Implemented augmented reality applications'
                              ]
                          }
                      ],
                      'skills': {
                          'Programming': ['Python', 'C++', 'MATLAB', 'JavaScript'],
                          'ML/AI': ['PyTorch', 'TensorFlow', 'OpenCV', 'ROS'],
                          'Tools': ['Git', 'Docker', 'LaTeX', 'Hugo']
                      },
                      'research_interests': [
                          'Reinforcement Learning',
                          'Computer Vision',
                          'Robotics',
                          'Curriculum Learning'
                      ]
                  }

          def generate_latex(data):
              """Generate LaTeX from resume data"""
              template = r'''
          \documentclass[11pt,a4paper]{article}
          \usepackage[margin=0.75in]{geometry}
          \usepackage{hyperref}
          \usepackage{enumitem}
          \usepackage{titlesec}
          \titleformat{\section}{\large\bfseries}{}{0em}{}[\titlerule]
          \titleformat{\subsection}{\bfseries}{}{0em}{}
          \setlength{\parindent}{0pt}
          \pagestyle{empty}

          \begin{document}

          \begin{center}
              {\LARGE \textbf{ {{ name }} }}\\[0.5em]
              {{ email }} | {{ phone }}\\
              \href{https://{{ website }}}{{{ website }}} | 
              \href{https://{{ linkedin }}}{LinkedIn} | 
              \href{https://{{ github }}}{GitHub}
          \end{center}

          \section{Education}
          {% for edu in education %}
          \subsection{ {{ edu.degree }} }
          {{ edu.institution }} \hfill {{ edu.year }}\\
          {{ edu.details }}
          {% endfor %}

          \section{Experience}
          {% for exp in experience %}
          \subsection{ {{ exp.title }} }
          {{ exp.company }} \hfill {{ exp.period }}
          \begin{itemize}[leftmargin=*,topsep=0pt,itemsep=0pt]
          {% for bullet in exp.bullets %}
              \item {{ bullet }}
          {% endfor %}
          \end{itemize}
          {% endfor %}

          \section{Skills}
          {% for category, items in skills.items() %}
          \textbf{ {{ category }} }: {{ items|join(', ') }}\\
          {% endfor %}

          \section{Research Interests}
          {{ research_interests|join(', ') }}

          \vfill
          \begin{center}
              \small\textit{Generated on {{ date }} | Version: {{ version }} }
          \end{center}

          \end{document}
              '''
              
              template_obj = Template(template)
              data['date'] = datetime.now().strftime('%B %d, %Y')
              data['version'] = os.environ.get('RESUME_VERSION', 'latest')
              
              return template_obj.render(**data)

          def main():
              # Load data
              data = load_resume_data()
              
              # Generate LaTeX
              latex_content = generate_latex(data)
              
              # Save LaTeX file
              with open('resume.tex', 'w') as f:
                  f.write(latex_content)
              
              # Compile to PDF
              subprocess.run(['pdflatex', 'resume.tex'])
              subprocess.run(['pdflatex', 'resume.tex'])  # Run twice for references
              
              # Create versioned filename
              timestamp = datetime.now().strftime('%Y%m%d')
              version = os.environ.get('RESUME_VERSION', 'latest')
              
              # Copy files to appropriate locations
              os.system(f'cp resume.pdf static/files/cv.pdf')
              os.system(f'cp resume.pdf "static/files/Linji Wang CV site-linji.pdf"')
              os.system(f'cp resume.pdf static/files/resume-versions/resume_{timestamp}_{version}.pdf')
              
              print(f"Resume generated successfully: resume_{timestamp}_{version}.pdf")

          if __name__ == '__main__':
              main()
          EOF

      - name: Generate sample resume data
        run: |
          mkdir -p content/resume
          cat > content/resume/data.yaml << 'EOF'
          name: "Linji (Joey) Wang"
          email: "joewwang@outlook.com"
          phone: "+1 412-888-6071"
          linkedin: "linkedin.com/in/linjiw"
          github: "github.com/linjiw"
          website: "linjiwang.com"

          education:
            - degree: "Ph.D. in Computer Science"
              institution: "George Mason University"
              year: "2023 - Present"
              details: "Research focus: AI, Robotics, Reinforcement Learning with Curriculum Learning"
            - degree: "M.Sc. in Mechanical Engineering"
              institution: "Carnegie Mellon University"
              year: "2021 - 2023"
              details: "Focus: Machine Learning and Computer Vision"
            - degree: "B.Sc. in Mechanical Engineering"
              institution: "University of Cincinnati"
              year: "2017 - 2021"
              details: "Summa Cum Laude, Dean's List"

          experience:
            - title: "Graduate Research Assistant"
              company: "George Mason University"
              period: "2023 - Present"
              bullets:
                - "Developing innovative reinforcement learning techniques for robotic systems"
                - "Focus on curriculum learning for efficient robot training"
            - title: "Teaching Assistant"
              company: "Carnegie Mellon University"
              period: "2022 - 2023"
              bullets:
                - "Assisted in Machine Learning (10-701) and Deep Learning courses"
                - "Mentored 50+ graduate students in project implementations"
                - "Developed tutorial materials for PyTorch and TensorFlow"
            - title: "Research Assistant"
              company: "Computational Engineering & Robotics Laboratory"
              period: "2021 - 2023"
              bullets:
                - "Developed computer vision algorithms for 3D scene understanding"
                - "Implemented AR applications for robotic manipulation"
                - "Published research on visual perception systems"

          skills:
            Programming: ["Python", "C++", "MATLAB", "JavaScript", "Julia"]
            "ML/AI Frameworks": ["PyTorch", "TensorFlow", "JAX", "OpenCV", "scikit-learn"]
            Robotics: ["ROS/ROS2", "Gazebo", "MoveIt", "SLAM"]
            Tools: ["Git", "Docker", "LaTeX", "Hugo", "Linux"]

          research_interests:
            - "Reinforcement Learning"
            - "Computer Vision"
            - "Robotics & Autonomous Systems"
            - "Curriculum Learning"
            - "Neural Architecture Search"

          publications:
            - "Curriculum Learning for Robotic Manipulation (In Progress)"
            - "Vision-based 3D Scene Understanding for AR Applications (CMU, 2023)"
          EOF

      - name: Generate Resume PDF
        env:
          RESUME_VERSION: ${{ github.event.inputs.version || 'latest' }}
        run: |
          python scripts/generate_resume.py

      - name: Create Resume Markdown Version
        run: |
          cat > content/resume/index.md << 'EOF'
          ---
          title: "Resume"
          date: ${{ steps.date.outputs.date }}
          draft: false
          ---

          # Linji (Joey) Wang

          [Download PDF Version](/files/cv.pdf)

          ## Contact
          - Email: joewwang@outlook.com
          - Phone: +1 412-888-6071
          - Website: [linjiwang.com](https://linjiwang.com)
          - LinkedIn: [linkedin.com/in/linjiw](https://linkedin.com/in/linjiw)
          - GitHub: [github.com/linjiw](https://github.com/linjiw)

          ## Education
          ... (Auto-generated from YAML data)
          EOF

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "Auto-generate resume PDFs [skip ci]"
          git push || echo "No changes to push"