name: Validate Content

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  validate-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install markdown-link-check
        run: npm install -g markdown-link-check
        
      - name: Check Markdown links
        run: |
          find . -name "*.md" -not -path "./node_modules/*" | xargs -I {} markdown-link-check {} || true
          
  validate-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check image sizes
        run: |
          echo "Checking for large images..."
          find . -name "*.jpg" -o -name "*.png" -o -name "*.jpeg" | while read img; do
            size=$(stat -f%z "$img" 2>/dev/null || stat -c%s "$img" 2>/dev/null)
            if [ "$size" -gt 2097152 ]; then
              echo "Warning: $img is larger than 2MB ($(($size / 1048576))MB)"
            fi
          done
          
  validate-hugo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.108.0'
          extended: true
          
      - name: Build and check for errors
        run: |
          hugo --gc --minify --buildDrafts
          if [ $? -ne 0 ]; then
            echo "Hugo build failed!"
            exit 1
          fi
          
      - name: Check for broken internal links
        run: |
          hugo --gc --minify --buildDrafts --baseURL "/" 
          # Simple check for 404s in generated HTML
          find public -name "*.html" -exec grep -l "404" {} \; | head -10
          
  validate-accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.108.0'
          extended: true
          
      - name: Build site
        run: hugo --gc --minify
        
      - name: Run Pa11y accessibility tests
        run: |
          npm install -g pa11y
          # Test main pages for accessibility
          pa11y ./public/index.html --reporter cli || true
          pa11y ./public/about/index.html --reporter cli || true